Feat e2e first install good experience
boomerang-io/charts pull request #37
Opened 2021-08-10 13:13 UTC by morarucostel

Closes 

Updated the chart to include the necessary dependencies. 

#### Changelog

**New**

- Added oauth2-proxy OSS as dependency
- Added tekton pipelines as dependency

**Changed**

- NA

**Removed**

- NA

#### Testing / Reviewing

Tested in our poc environment

2021-08-10 22:46 UTC, tlawrie commented on examples/e2e-flow-github-auth-values.yaml
> +    zone: untrusted
Do you think for the example we leave the versions out? that way we only have to keep them updated in the main values.yaml which is hard enough to keep in sync.

2021-08-11 08:23 UTC, morarucostel commented on examples/e2e-flow-github-auth-values.yaml
> +    zone: untrusted
Totally agree with you, I missed that part.
I'll remove the image tags.

2021-08-11 08:27 UTC, tlawrie commented on examples/e2e-flow-github-auth-values.yaml
> +    zone: untrusted
Thanks @morarucostel . Also potentially the `e2e` in the file title.

2021-08-11 09:52 UTC, morarucostel commented
@tlawrie done&done.

2021-08-12 01:03 UTC, tlawrie requested changes

2021-08-12 01:03 UTC, tlawrie commented on examples/flow-github-auth-values.yaml
> +    root: /poc-standalone/flow
And everywhere its referenced like namespaces

2021-08-12 07:11 UTC, tlawrie approved these changes

2021-08-12 07:11 UTC, merged